
"""updating database schema

Revision ID: 18631ac7a632
Revises: 
Create Date: 2025-10-22 13:24:51.968941

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18631ac7a632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
