
"""add refresh_tokens

Revision ID: 1c76a919e523
Revises: 18631ac7a632
Create Date: 2025-10-22 13:58:19.747444

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c76a919e523'
down_revision = '18631ac7a632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
