
"""created User Model

Revision ID: b2979992e214
Revises: 
Create Date: 2025-10-20 15:47:56.448550

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2979992e214'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('user_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_authors_user_id'), 'authors', ['user_id'], unique=True)
    op.create_foreign_key(None, 'authors', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_index(op.f('ix_authors_user_id'), table_name='authors')
    op.drop_column('authors', 'user_id')
    # ### end Alembic commands ###
