
"""created BlacklistedToken Model

Revision ID: c5d4ca16f668
Revises: 1c76a919e523
Create Date: 2025-10-24 16:24:13.499358

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d4ca16f668'
down_revision = '1c76a919e523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
