openapi: 3.0.0
info:
  title: 'Books Inventory API'
  description: 'A books Inventory API that keeps stock of books'
  version: 1.0.0

servers:
  - url: '/api'

paths:
  /books:
    get:
      operationId: api.books.read_all
      tags:
        - 'Books'
      summary: 'Read the list of books'
      responses:
        '200':
          description: 'Sucessfully read books list'