openapi: 3.0.0
info:
  title: "Books Inventory API"
  description: "A books Inventory API that keeps stock of books"
  versio: "1.0.0"

server:
  - url: "/api"

paths:
  /books:
    get:
      operationId: "books.read_all"
      tags:
        - "Books"
      Summary: "Read the list of books"
      responses:
        "200":
          description: "Sucessfully read books list"